### ISSUE TITLE
Gmfs by event-based calc don't have color formatting

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#758]
![QGIS-gmfs_from_event_based](https://user-images.githubusercontent.com/350930/107626154-aae7ac00-6c5d-11eb-8e29-71ded571201f.png)

**Comment by ptormene** [comment]
@CatalinaYepes, please, could you check that values are not all equal to each other? I've tried loading gmfs from Stochastic Event-Based Damage Demo (Nepal) and points are all the same for PGA but they are not for SA(0.3). When at least 2 points have different values, you should see different colors.

**Comment by CatalinaYepes** [comment]
I confirm that the layer had all zeros for PGA and if other layers with non-zero values are selected then the plugin shows the correct colours.

However, when trying to select another event I found that the plugin has a behaviour a bit unexpected:
 
1. In the `Select an event ID` window a range of events is displayed, e.g. `Rage (76795 - 171982)`
2. The user can type the number of the event in that range, e.g. `90000`, and then click `OK` button
3. Once again the `Select an event ID` window appears but the event ID says `90230`. The user writes again the `90000` and the loop with enters and the desired event ID can go forever.

I'm assuming the reason is that there is not an event with a `90000` ID, and the plugin returns the closest ID. Is that correct? 
If yes, I don't think the behaviour is user-intuitive and the way we are plotting event-based gmfs is not very meaningful. We should think on better alternatives, considering that the EB calculator returns thousands of events which are not close to zero and the user instead might be interested in visualising events for a given risk metric (for example, maximum losses or a range of return periods)

**Comment by ptormene** [comment]
Yes @CatalinaYepes, you guessed correctly. The plugin in fact returns the closest event ID. Indeed it would be good discussing about alternative approaches on how to cope with thousands of events.
